### ISSUE TITLE
Add Path Functionality

### ISSUE THREAD

**Issue by GalGreenfield** [aerys/gpm#10]
Hello,

Could you please add the functionality to supply path functionality, to manage packages in a location of the user's choosing? It'd would be VERY helpful.

**Comment by JMLX42** [comment]
Hello,

Thank you for your suggestion.
What do you mean by "Path"?

1. The path where the package should be installed/downloaded locally.
2. Or the path where to look for packages inside the Git package repository.
3. Or something else?

Please give an example of the command line you would like to use and the expected outcome.

**Comment by GalGreenfield** [comment]
I meant something closer to 1. - included path functionality to choose location of installation, and for `gpm` to store that path to be able to manage it - update, move, and delete.

**Comment by JMLX42** [comment]
Option 1 is already handled via the `--prefix` option for the `install` command.

Regarding package tracking, it's already being discussed in #3 .

Unless you have anything else to add, please close this issue.

**Comment by GalGreenfield** [comment]
Oh, I must have missed that flag, thank you!
