### ISSUE TITLE
Where are the sources on Windows?

### ISSUE THREAD

**Issue by GalGreenfield** [aerys/gpm#13]
What's the path of the sources file on Windows?

**Comment by JMLX42** [comment]
> What's the path of the sources directory in Windows?

@GalGreenfield what do you mean exactly when you say "sources"?

If you mean the `.gpm` folder it's in the home directory of the user.

**Comment by GalGreenfield** [comment]
> > What's the path of the sources directory in Windows?
> 
> @GalGreenfield what do you mean exactly when you say "sources"?
> 
> If you mean the `.gpm` folder it's in the home directory of the user.

Firstly, do notice the my update of the post - I re-read the docs and its a file.

And I mean the file sources.list - on Linux it's where you said - I'm asking where it is on Windows.

**Comment by JMLX42** [comment]
> And I mean the file sources.list - on Linux it's where you said - I'm asking where it is on Windows.

On Windows it is in the "same location" : `$home/.gpm/sources.list`. But it does not exist by default: it must be created.

**Comment by GalGreenfield** [comment]
> > And I mean the file sources.list - on Linux it's where you said - I'm asking where it is on Windows.
> 
> On Windows it is in the "same location" : `$home/.gpm/sources.list`. But it does not exist by default: it must be created.

But Windows does not have a `$home` directory as it doesn't use Linux's file system.

**Comment by GalGreenfield** [comment]
bump

**Comment by GalGreenfield** [comment]
More than half a year and still no reply.
So **where** am I supposed to create `sources.list` on Windows?

**Comment by JMLX42** [comment]
> More than half a year and still no reply.

@GalGreenfield more than a year and you apparently did not even try: yes, there is a `$home` on Windows.

![image](https://user-images.githubusercontent.com/998703/218973831-61b4b81b-c8f3-4ec0-a336-899ef11413ae.png)

You can also use a search engine:

- https://stackoverflow.com/questions/9228950/what-is-the-alternative-for-users-home-directory-on-windows-command-prompt
- https://stackoverflow.com/questions/54983954/is-there-an-alias-for-the-home-folder-in-windows-10

And you can also simply read the docs of `dirs` (used [here](https://github.com/aerys/gpm/blob/916bae43446a430fd04c9ec84419aebf666ea775/src/gpm/file.rs)): 

https://docs.rs/dirs/4.0.0/dirs/fn.home_dir.html
