### ISSUE TITLE
[Question] Submodules vs GPM

### ISSUE THREAD

**Issue by alexmozaidze** [aerys/gpm#16]
I am curious as to how GPM compares to just using vanilla git submodules.

**Comment by JMLX42** [comment]
To init/clone submodules, you need :

- git and it's dependencies
- some script to recursively clone only the submodule (package?) you want to install

And a submodule is stuck to a specific commit (version ?).

With GPM, you just need:

- `gpm` (0 dependencies)
- the package / version name

**Comment by alexmozaidze** [comment]
Ak
