### ISSUE TITLE
Push more then one packages at once?

### ISSUE THREAD

**Issue by pwFoo** [aerys/gpm#4]
Hi,
is it needed to push each single package because of the tag?
I haven't much experience with git and haven't worked with tags before.

**Comment by JMLX42** [comment]
> is it needed to push each single package because of the tag?

Just create a commit/tag for each package release:

```bash
git commit ${PACKAGE}/${PACKAGE}.tar.gz -m "Publish ${PACKAGE} version ${VERSION}."
git tag ${PACKAGE}/${VERSION}
```

and then push everything:

```bash
git push
git push --tags
```

**Comment by ahoeg** [comment]
Hi, 
so single push is ok, but each package release needs it's own commit + tag.
So release 3 packages needs 3 commits, 3 tags and 1 push / push tags.

Thanks!

**Comment by pwFoo** [comment]
Hi,
so single push is ok, but each package release needs it's own commit + tag.
So release 3 packages needs 3 commits, 3 tags and 1 push / push tags.

Thanks!
