### ISSUE TITLE
Unable to install specific version, only latest

### ISSUE THREAD

**Issue by johnmorrell** [aerys/gpm#8]
GPM: 0.15.0
OS: macOS
Package Repo: GitHub (private)

I am unable to install a specific package version, only the latest. Following the example in the docs:

```
gpm install hello-world/0.1.0 --prefix ~/
```

I get an error:

```
johnmorrell@MacBook-Pro gpm % gpm install ssh://github.com/[redacted]/packages.git#[redacted]/0.1.17 --prefix /usr/local/bin --force

Installing package [redacted]/0.1.17
[1/3] Resolving package
 ERROR gpm > GPM command error: no matching version for package [redacted]/0.1.17
```

Using an `@` rather than `/` identifies the specified version but installs the latest:

```
johnmorrell@MacBook-Pro gpm % gpm install ssh://github.com/[redacted]/packages.git#[redacted]@0.1.17 --prefix /usr/local/bin --force

Installing package [redacted]0.1.17
[1/3] Resolving package
  Found:
    [redacted].tar.gz
  in:
    ssh://github.com/[redacted]/packages.git
  at refspec:
    refs/tags/[redacted]/0.1.18
  tagged as:
    [redacted]/0.1.18
[2/3] Downloading package
  [00:00:04] [##############################] 517.94KB/517.94KB (0s)
[3/3] Extracting package in "/usr/local/bin"
  [00:00:00] Archive decompressed
  [00:00:00] 1/1 extracted file(s)
Done!
```

Thank you for sharing your work and looking in to these issues!

**Comment by JMLX42** [comment]
IMHO that's not a bug, but [the documentation](https://github.com/aerys/gpm#8-package-reference-notation
) is not up to date;

```
gpm install hello-world/0.1.0 --prefix ~/
```

should be:

```
gpm install hello-world=0.1.0 --prefix ~/
```

(and it expects an actual `0.1.0` tag to work)

> Using an @ rather than / identifies the specified version but installs the latest:

`@` is used to identify any git refspec rather a semver compliant tag.

**Comment by johnmorrell** [comment]
Thanks @promethe42, that makes sense and works great.

I'll leave this issue open for the documentation update.

**Comment by JMLX42** [comment]
Thanks. Fixed.
